# Site settings
title: Benjamin Arnav
# Site's name
name: Benjamin Arnav's Portfolio
author: Benjamin Arnav
author_nickname: Benjamin Arnav
email: contact_arnav.darkened639@8alias.com
description: ""
baseurl: ""
url: "https://benarnav.github.io"
exclude: [vendor]

future: false

repo:
  repository_url: https://github.com/benarnav/benarnav.github.io
  branch: main

permalink: '/'
post_dirs: false

include:
  - "assets/audio/parking_monitor_podcast.mp3"
  - "assets/iframes/parking_monitor_map.html"

# Build settings
markdown: kramdown
kramdown:
  input: GFM # GitHub Flavored Markdown
  hard_wrap: false
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - rouge

collections:
  blog:
    output: true
    permalink: /blog/


default_og_image: "/favicon.ico"
